[Service]
ExecStart=
ExecStart=-/usr/bin/bash -c '/usr/bin/agetty --noclear --autologin $((grep -q "script=/root/scripts/install-to-disk.sh" /proc/cmdline && echo root) || (grep -q "script=/root/scripts/auto-install.sh" /proc/cmdline && echo root) || (grep -q "script=/home/soaktest/scripts/soak-test.sh" /proc/cmdline && echo soaktest) || echo feralfile) %I $TERM'
