[Service]
# bluetoothd does not respect DisablePlugins in main.conf anymore; invoke it
# without the battery plugin so our provisioning channel stays stable.
ExecStart=
ExecStart=/usr/lib/bluetooth/bluetoothd --noplugin=battery
