title   24H Soak test for FF1
linux   /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux
initrd  /%INSTALL_DIR%/boot/x86_64/initramfs-linux.img
initrd  /%INSTALL_DIR%/boot/intel-ucode.img
options archisobasedir=%INSTALL_DIR% archisodevice=UUID=%ARCHISO_UUID% cow_spacesize=1G script=/home/soaktest/soak-test.sh ipv6.disable=1
